### ISSUE TITLE
Random variability in quest configuration

### ISSUE THREAD

**Issue by vasekhodina** [G3rste/vsquest#3]
I think it would help if there was an option to configure range of any number in quest configuration. The final value would be chosen pseudorandomly.
Examples of what I mean:
Quest shows again 3 to 6 days after completion.
Quest reward is 2 - 5 rusty gears.
Quest objective is to bring 100 - 10 000 black steel ingots.

Another higher level would be to randomly choose one of multiple values.
Kill 10 wolves or drifters => Only wolves would be chosen, so the quest would be about killing 10 wolves.
Receive reward of 20 oak or birch planks => 20 oak planks would be received.
This could be picked when the quest is generated.

**Comment by G3rste** [comment]
I added a possibility to configure randomly chosen rewards additionally to the deterministic ones in the last update.
[Here is a short description of how to implement the random rewards.](https://github.com/G3rste/vsquest/blob/master/README.md?plain=1#L27-L32)
[And here is an example.](https://github.com/G3rste/vsvillage/blob/master/resources/assets/vsvillage/config/quests.json#L230-L264)

Randomizing other things than the rewards would require to change the architecture I went with so far, so I am going to leave that be for now.

**Comment by vasekhodina** [comment]
Awesome, thanks.
